Repository cdktf/cdktf-provider-project, pull requests merged in 2023-10, with the labels that each got.

#345 chore: fix broken upgrade-node workflow
  .projen/deps.json
  .projen/tasks.json
  .projenrc.ts
  package.json
  yarn.lock
Labels: automerge, auto-approve

#346 chore: remove compile step and just have that fail during build
  .github/workflows/upgrade-node.yml
  projenrc/upgrade-node.ts
Labels: automerge, auto-approve

#348 chore: add missing checkout step to autoclose workflows
  src/auto-close-community-issues.ts
  test/__snapshots__/index.test.ts.snap
Labels: automerge, auto-approve

#349 chore: improve identity checks in autoclose workflow
  src/auto-close-community-issues.ts
  test/__snapshots__/index.test.ts.snap
Labels: automerge, auto-approve

#344 chore(deps): upgrade dependencies
  package.json
  test/index.test.ts
  yarn.lock
Labels: dependencies

#352 chore: don't attempt to delete the branch when autoclosing community PRs
  src/auto-close-community-issues.ts
  test/__snapshots__/index.test.ts.snap
Labels: automerge, auto-approve

#347 chore!: increase minimum supported Node.js version to 18
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-main.yml
  .projen/deps.json
  .projenrc.ts
  package.json
  yarn.lock
Labels: automated, automerge, security
