Repository cdktf/cdktf-provider-project, pull requests merged in 2023-12, with the labels that each got.

#364 chore(deps): upgrade dependencies
  yarn.lock
Labels: dependencies

#366 chore: fix typo in provider-upgrade workflow
  src/provider-upgrade.ts
  test/__snapshots__/index.test.ts.snap
Labels: automerge, auto-approve

#367 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: dependencies

#373 chore: miscellaneous cleanup
  .projenrc.ts
  package.json
  src/cdktf-config.ts
  src/force-release.ts
  src/index.ts
  src/next-version-pr.ts
  src/semver.ts
  test/__snapshots__/index.test.ts.snap
Labels: automerge, auto-approve

#374 chore: copy the README in the Go repo instead of moving it
  src/force-release.ts
  src/index.ts
  test/__snapshots__/index.test.ts.snap
Labels: automerge, auto-approve

#375 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: dependencies, automerge

#376 fix: make sure release works for deprecated providers
  src/index.ts
  test/__snapshots__/index.test.ts.snap
Labels: automerge, auto-approve

#377 fix: address problems uncovered when testing deprecating Hashicups
  src/deprecate-packages.ts
  src/index.ts
  test/__snapshots__/index.test.ts.snap
Labels: automerge, auto-approve

#378 chore: clean up deprecation work
  src/deprecate-packages.ts
  src/force-release.ts
  src/index.ts
  src/readme.ts
  test/__snapshots__/index.test.ts.snap
Labels: automerge, auto-approve

#380 chore(ci): update actions/stale workflow
  src/index.ts
  test/__snapshots__/index.test.ts.snap
Labels: automerge, auto-approve
