Repository cdktf/cdktf-provider-project, pull requests merged in 2025-06, with the labels that each got.

#503 chore(deps): upgrade dependencies
  yarn.lock
Labels: dependencies, automerge, auto-approve

#504 chore(deps): upgrade jsii & typescript to v5.7 in this project only
  .github/workflows/upgrade-jsii-typescript.yml
  .projen/deps.json
  .projenrc.ts
  package.json
  yarn.lock
Labels: automated, automerge, auto-approve

#492 chore!: increase minimum supported Node.js version to 20 for this project only
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-jsii-typescript.yml
  .github/workflows/upgrade-main.yml
  .github/workflows/upgrade-node.yml
  .projen/deps.json
  .projenrc.ts
  package.json
  src/index.ts
  test/__snapshots__/index.test.ts.snap
  yarn.lock
Labels: automated, automerge, security

#507 refactor: make force-release workflow more resilient
  src/force-release.ts
  test/__snapshots__/index.test.ts.snap
Labels: automerge, auto-approve

#510 chore(deps): upgrade dependencies
  yarn.lock
Labels: dependencies, automerge, auto-approve
