Repository cdktf/cdktf-provider-project, pull requests merged in 2025-01, with the labels that each got.

#465 chore(deps): upgrade dependencies
  test/__snapshots__/index.test.ts.snap
  yarn.lock
Labels: dependencies, automerge, auto-approve

#466 chore(ci): prevent PRs by Dependabot from auto-closing
  src/auto-close-community-issues.ts
  test/__snapshots__/index.test.ts.snap
Labels: automerge, auto-approve

#467 chore(deps): update pinned versions of GitHub Actions
  .github/workflows/auto-approve.yml
  .github/workflows/automerge.yml
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-main.yml
  .github/workflows/upgrade-node.yml
  .projenrc.ts
  src/index.ts
  test/__snapshots__/index.test.ts.snap
Labels: automerge, auto-approve

#470 chore(ci): add workflow for upgrading jsii & typescript
  .gitattributes
  .github/workflows/upgrade-jsii-typescript.yml
  .gitignore
  .projen/files.json
  .projenrc.ts
  projenrc/scripts/check-jsii-versions.js
  projenrc/scripts/upgrade-jsii-typescript.sh
  projenrc/upgrade-jsii-typescript.ts
Labels: automerge, auto-approve

#469 chore(ci): pin version of cssstyle to allow upgrade-main to succeed
  .github/workflows/upgrade-node.yml
  .projen/deps.json
  .projenrc.ts
  package.json
  projenrc/upgrade-node.ts
  src/index.ts
  test/__snapshots__/index.test.ts.snap
  yarn.lock
Labels: automerge, auto-approve

#472 chore(ci): make upgrade-node workflow manually triggerable
  .github/workflows/upgrade-node.yml
  projenrc/scripts/check-node-versions.js
  projenrc/upgrade-node.ts
Labels: automerge, auto-approve

#473 chore(ci): address workflow consistency issues
  .github/workflows/auto-approve.yml
  .github/workflows/automerge.yml
  .github/workflows/upgrade-jsii-typescript.yml
  projenrc/upgrade-jsii-typescript.ts
  projenrc/upgrade-node.ts
  src/alert-open-prs.ts
  src/auto-approve.ts
  src/auto-close-community-issues.ts
  src/automerge.ts
  src/deprecate-packages.ts
  src/lock-issues.ts
  src/provider-upgrade.ts
  test/__snapshots__/index.test.ts.snap
Labels: automerge, auto-approve

#474 chore(ci): don't cancel-in-progress auto-approve and automerge workflows
  .github/workflows/auto-approve.yml
  .github/workflows/automerge.yml
  src/auto-approve.ts
  src/automerge.ts
  test/__snapshots__/index.test.ts.snap
Labels: automerge, auto-approve

#475 chore(deps): upgrade dependencies
  yarn.lock
Labels: dependencies, automerge, auto-approve

#468 chore(deps): update pinned versions of GitHub Actions
  src/alert-open-prs.ts
  src/index.ts
  test/__snapshots__/index.test.ts.snap
Labels: automerge, auto-approve

#476 chore(deps): upgrade dependencies
  yarn.lock
Labels: dependencies, automerge, auto-approve

#477 chore(ci): fix workflow erroring due to file misname
  projenrc/scripts/update-jsii-typescript.sh
Labels: automerge, auto-approve

#478 chore(ci): fix workflow erroring due to root directory mismatch
  projenrc/scripts/update-jsii-typescript.sh
Labels: automerge, auto-approve

#479 chore(deps): upgrade jsii & typescript to v5.5 in this project only
  .github/workflows/upgrade-jsii-typescript.yml
  .projen/deps.json
  .projenrc.ts
  package.json
  yarn.lock
Labels: automated, automerge, auto-approve
